/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 credit.gltf 
Author: Aya Dja (https://sketchfab.com/ayadja1977)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/credit-card-4c4117d766f342cc9e0fa3d79e9de654
Title: Credit card
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/credit.gltf')
  return (
    <group {...props} dispose={null}>
        <group scale={0.300} >
      <group position={[0.033, 0.851, -4.527]} rotation={[0, 0, -Math.PI / 2]} scale={[3.399, 1.304, 5.474]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.border} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.inside} />
      </group>
      <group position={[-0.106, 0.837, -4.543]} rotation={[0, 0, -Math.PI / 2]} scale={[3.394, 1, 5.471]}>
        <mesh geometry={nodes.Object_9.geometry} material={materials.card_face_1} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.border_card} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.black_back} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.back} />
      </group>
      <mesh geometry={nodes.Object_7.geometry} material={materials.numbers} position={[-0.028, 0.851, -4.527]} rotation={[0, 0, -Math.PI / 2]} scale={[3.399, 0.594, 5.474]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.material} position={[-0.106, 0.837, -4.543]} rotation={[0, 0, -Math.PI / 2]} scale={[3.394, 1, 5.471]} />
    </group>
    </group>
  )
}

useGLTF.preload('/credit.gltf')
